### ISSUE TITLE
Formatting and timings minor issues

### ISSUE THREAD

**Issue by AlessioDelConte** [deemeng/punch_linker#4]
Dear Di,

I've tested the predictor and it works perfectly.
Just two minor issues that I've encountered:

- In the timings.csv file the reported value should be the number of milliseconds it took the predictor to run, so if it took 200ms it should be reported as 200
- In the formatting of the output prediction, the probability score should be formatted to the 3rd decimal value like so: 0.864

If you can adjust these small things it would be super helpful,
Many thanks,
Alessio

**Comment by deemeng** [comment]
HI Alessio,

That's great! I will edit those two parts and let you know when I finish.

Best.
Di.

**Comment by deemeng** [comment]
Hi Alessio,

Please check dimeng851/punch_linker:v2

Let me know if there are any issues.

Best.
Di.

**Comment by AlessioDelConte** [comment]
Thanks, now its perfect!
